<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.7.2 on win32)" generated="20200619 17:22:49.967" rpa="false">
<suite id="s1" name="Test" source="C:\Users\arun\PycharmProjects\RobotAutomation\TestData\Test.robot">
<test id="s1-t1" name="Test Login credential">
<kw name="Open Browser" library="SeleniumLibrary">
<doc>Opens a new browser instance to the optional ``url``.</doc>
<arguments>
<arg>https://facebook.com</arg>
<arg>Chrome</arg>
</arguments>
<msg timestamp="20200619 17:22:51.065" level="INFO">Opening browser 'Chrome' to base url 'https://facebook.com'.</msg>
<status status="PASS" starttime="20200619 17:22:51.064" endtime="20200619 17:23:02.428"></status>
</kw>
<kw name="Read Number of Rows">
<arguments>
<arg>Sheet1</arg>
</arguments>
<msg timestamp="20200619 17:23:02.481" level="FAIL">No keyword with name 'Read Number of Rows' found.</msg>
<status status="FAIL" starttime="20200619 17:23:02.480" endtime="20200619 17:23:02.481"></status>
</kw>
<status status="FAIL" starttime="20200619 17:22:51.061" endtime="20200619 17:23:02.487" critical="yes">No keyword with name 'Read Number of Rows' found.</status>
</test>
<status status="FAIL" starttime="20200619 17:22:49.978" endtime="20200619 17:23:02.500"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Test">Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200619 17:22:51.053" level="ERROR">Error in file 'C:\Users\arun\PycharmProjects\RobotAutomation\TestData\Test.robot' on line 3: Error in file 'C:\Users\arun\PycharmProjects\RobotAutomation\Resources\Userkeyword.robot' on line 10: Resource file with 'Test Cases' section is invalid.</msg>
</errors>
</robot>
